//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABCIntegration
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int branch_id { get; set; }
        public string branch_code { get; set; }
        public string addy_line1 { get; set; }
        public string addy_line2 { get; set; }
        public string city { get; set; }
        public string county { get; set; }
        public string country { get; set; }
        public string postcode { get; set; }
        public int manager_id { get; set; }
    }
}
