/*
Deployment script for b4039403

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "b4039403"
:setvar DefaultFilePrefix "b4039403"
:setvar DefaultDataPath "E:\AWT\"
:setvar DefaultLogPath "E:\AWT\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[Parcel].[branch_id] (SqlSimpleColumn) will not be renamed to branch_code';


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Altering [dbo].[Parcel]...';


GO
ALTER TABLE [dbo].[Parcel]
    ADD [branch_code]         NCHAR (10)    NOT NULL,
        [shipping_addy_line1] NVARCHAR (50) NULL,
        [shipping_addy_line2] NVARCHAR (50) NULL,
        [shipping_city]       NVARCHAR (50) NULL,
        [shipping_county]     NVARCHAR (50) NULL,
        [shipping_country]    NVARCHAR (50) NULL,
        [shipping_postcode]   NCHAR (10)    NULL,
        [tracking_id]         NVARCHAR (50) NULL,
        [shipping_mode]       NVARCHAR (50) NULL;
	[date_create] DATE NOT NULL;
	[creator_id] INT NULL; 


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
